### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by Choeoqe** [roxy-wi/roxy-wi#177]
Hi, is the repository still working for this? I am not finding the package when I try and install.

Thanks!

**Comment by Aidaho12** [comment]
Hi,

Yes it's still works, but for access to  repository needs credentials. How get them you can read here https://haproxy-wi.org/installation.py

**Comment by Choeoqe** [comment]
Perfect, thank you!

**Comment by Aidaho12** [comment]
You are welcome:)

**Comment by Trylat** [comment]
When I try to install manually roxy, I got a Error for the step where you use the command
`sudo a2ensite roxy-wi.conf`
the error says:` ERROR: Site roxy-wi does not exist!`
What can I do to fix it ?
Thanks

**Comment by Aidaho12** [comment]
You can create config

**Comment by Aidaho12** [comment]
The repositories are now open
