### ISSUE TITLE
Issue with installation of Haproxy, nodes exporter

### ISSUE THREAD

**Issue by netsysadm** [roxy-wi/roxy-wi#297]
Hi,

I believe there is an issue with the haproxy, nginx, nodes exporter

**Comment by Aidaho12** [comment]
There is an answer in the error. Read the installation instructions carefully

**Comment by netsysadm** [comment]
thanks @Aidaho12 but the Haproxy exporter is still not being installed, may I know where do I can find the logs for it, as the notification itself only shows a blue bar.

![image](https://user-images.githubusercontent.com/56064755/137341153-ebe44dfb-b3f7-4351-a9bc-458b9613f885.png)
