### ISSUE TITLE
Letsencrypt with multiple domain in one certificate

### ISSUE THREAD

**Issue by baoc75** [roxy-wi/roxy-wi#363]
Hello,
Assume that I want to generate SSL certificate for www.abc.com and abc.com. I will type into the domain fields as `www.abc.com,abc.com`. Certbot still understand that, but the cert concat process will include the comma "," which makes the file won't work anymore thus the certificate won't saved in /etc/ssl/certs.
Now if I generate one by one then it will be stuck as certbot ask whether I want to update the existing one by press "Y"

**Comment by Aidaho12** [comment]
Hello,
If delete wrong certificates, will it work?

We will investigate about comma

**Comment by baoc75** [comment]
It won't work because it can't write to filename with comma character. When I open that file `www.abc.com,abc.com.pem`, it exist but is an empty file. The app also throw errors too (definitely not related to Certbot as the cert already created)

**Comment by Aidaho12** [comment]
No, I meant does it work for one certificate?

**Comment by baoc75** [comment]
Oh it works very well if you generate certificate for 1 domain like "abc.com".

**Comment by Aidaho12** [comment]
Ok, thank you. Will try to fix it
