### ISSUE TITLE
Change language to not use master and slave

### ISSUE THREAD

**Issue by joakimkingstrom** [roxy-wi/roxy-wi#374]
Hi,

We're looking at starting to trial and use roxy-wi in my company but some of the language used in the GUI does not rhyme with our values, something which can be an obstacle for us.

I realise that some people see it as an empty gesture, but even empty gestures are sometimes worth doing, especially if there are no drawbacks to doing them.

It'd therefore be great if the terms master and slave can be changed to what the rest of the industry is using nowadays, for example primary and secondary/replica/follower/etc.

We'd highly appreciate it and it'd make the road to purchasing licenses a lot easier for us, and most likely a lot of other companies.

Kind regards,
Joakim Kingström

**Comment by Aidaho12** [comment]
Hello, of course this is not a problem.  Could you please notify me when you purchase licenses, I will correct the text by that date
