### ISSUE TITLE
Emojis in config files seem to cause problems

### ISSUE THREAD

**Issue by krisavi** [roxy-wi/roxy-wi#379]
If emoji in config file, then getting error like: 
`Cannot get sections from config file 'ascii' codec can't decode byte 0xf0 in position 3757: ordinal not in range(128)`

It seems haproxy handles emojis just fine, but roxy-wi is not able to parse emojis in acl
In haproxy config I have lines like... 
`    acl snakey hdr(host) -i 🐍.my.tld`

**Comment by Aidaho12** [comment]
Does it looks like:
```
frontend test
    mode http
    maxconn 2000
    acl snakey hdr(host) -i :snake:.my.tld
```
in your config? I cannot reproduce it

**Comment by krisavi** [comment]
In the config even if I open with vim it shows as snake emoji 🐍, not `:snake:`

Removing those lines, even if commented resolved the issue, but of course made it not to detect those edge case subdomain redirections.

**Comment by krisavi** [comment]
cat -A shows it like that:
`acl photos hdr(host) -i M-pM-^_M-^PM-^M.my.tld$`

**Comment by Aidaho12** [comment]
![Screenshot 2024-04-27 at 09 31 36](https://github.com/roxy-wi/roxy-wi/assets/20718301/5f890892-60fa-47a9-a3b1-5eed6c46c28c)
Well, it works
