### ISSUE TITLE
Hardcoded secret key

### ISSUE THREAD

**Issue by FHantke** [roxy-wi/roxy-wi#383]
Hello roxy-wi developers,

We are a cybersecurity research group from the CISPA Helmholtz Center for Information Security and Ca’ Foscari University of Venice. We recently conducted an analysis of the session management used in your web application as part of our research. We have discovered a security vulnerability that we believe requires your attention.

Vulnerability Description:

After our analysis, we have identified that your application is using a hard-coded secret key that is leaked through GitHub. If operators  who install your web application do not change this secret key, they are vulnerable to cookie forgeries. The cookie forgery attack allows an attacker, knowing the key used to sign a cookie, to forge new arbitrary cookies to impersonate and take over other accounts.

https://github.com/roxy-wi/roxy-wi/blob/b66c4d079330ea2f7c9c6da42099e88126f1bd31/app/config.py#L2

Recommendation for Mitigation:

To address this vulnerability and enhance the security posture of your web application, we highly recommend setting the secret key from an environment variable. If the environment file is not shared on GitHub then this would force operators of your application to create  their own key upon installation, forcing them to set their own secure secret key.

We hope this notification helps improve your security. Should you have further questions or comments on this feel free to answer this thread or reach out to florian.hantke@cispa.de

Kind regards,
Florian Hantke

**Comment by Aidaho12** [comment]
Hello, thank you. We are know about it and that's ok
