### ISSUE TITLE
Apache fails to install completely

### ISSUE THREAD

**Issue by JohnnyFastfox** [roxy-wi/roxy-wi#385]
Apache fails to install with the following error:
`May 29 13:03:41 error: Cannot install apache: error: cannot get server info: error: <Model: SystemInfo> instance matching query does not exist:
SQL: SELECT "t1"."id", "t1"."server_id", "t1"."os_info", "t1"."sys_info", "t1"."cpu", "t1"."ram", "t1"."disks", "t1"."network" FROM "system_info" AS "t1" WHERE ("t1"."server_id" = ?) LIMIT ? OFFSET ?
Params: [1, 1, 0] in function: select_os_info in file: server.py from x.x.x.x`

Also HAProxy is not installed with the proper selected version but rather from the distribution package provider (shows "2.0.33-0ubuntu0.1" even tho version 2.9.6-1 was selected and that happens even after I've apt purged HAProxy and it doesn't update on the selected version either)

I'm a Patreon supporter (1 year "Home" plan) and I'm quite frustrated.

**Comment by Aidaho12** [comment]
Hello, looks like Roxy-WI could not get info about the server when you added it. Try to update system info.

About haproxy, version selection works only for centos

**Comment by Aidaho12** [comment]
Check is there lshw program

**Comment by JohnnyFastfox** [comment]
Yes, running on both machines.

**Comment by Aidaho12** [comment]
Could you send me output lshw --json from the server where installation falls

**Comment by JohnnyFastfox** [comment]
{
  "id" : "8915",
  "class" : "system",
  "claimed" : true,
  "handle" : "DMI:0100",
  "description" : "Computer",
  "product" : "KVM",
  "vendor" : "Red Hat",
  "version" : "RHEL 7.6.0 PC (i440FX + PIIX, 1996)",
  "width" : 64,
  "configuration" : {
    "boot" : "normal",
    "family" : "Red Hat Enterprise Linux",
    "uuid" : "CF5F53E6-AC5A-2D42-8B14-152DCEFFFD93"
  },
  "capabilities" : {
    "smbios-2.8" : "SMBIOS version 2.8",
    "dmi-2.8" : "DMI version 2.8",
    "vsyscall32" : "32-bit processes"
  },
  "children" : [
    {
      "id" : "core",
      "class" : "bus",
      "claimed" : true,
      "description" : "Motherboard",
      "physid" : "0",
      "children" : [
        {
          "id" : "firmware",
          "class" : "memory",
          "claimed" : true,
          "description" : "BIOS",
          "vendor" : "SeaBIOS",
          "physid" : "0",
          "version" : "1.11.0-2.el7",
          "date" : "04/01/2014",
          "units" : "bytes",
          "size" : 98304
        },
        {
          "id" : "cpu",
          "class" : "processor",
          "claimed" : true,
          "handle" : "DMI:0400",
          "description" : "CPU",
          "product" : "QEMU Virtual CPU version 2.5+",
          "vendor" : "Intel Corp.",
          "physid" : "400",
          "businfo" : "cpu@0",
          "version" : "RHEL 7.6.0 PC (i440FX + PIIX, 1996)",
          "slot" : "CPU 0",
          "units" : "Hz",
          "size" : 2000000000,
          "capacity" : 2000000000,
          "width" : 64,
          "configuration" : {
            "cores" : "1",
            "enabledcores" : "1",
            "threads" : "1"
          },
          "capabilities" : {
            "fpu" : "mathematical co-processor",
            "fpu_exception" : "FPU exceptions reporting",
            "wp" : true,
            "de" : "debugging extensions",
            "pse" : "page size extensions",
            "tsc" : "time stamp counter",
            "msr" : "model-specific registers",
            "pae" : "4GB+ memory addressing (Physical Address Extension)",
            "mce" : "machine check exceptions",
            "cx8" : "compare and exchange 8-byte",
            "apic" : "on-chip advanced programmable interrupt controller (APIC)",
            "sep" : "fast system calls",
            "mtrr" : "memory type range registers",
            "pge" : "page global enable",
            "mca" : "machine check architecture",
            "cmov" : "conditional move instruction",
            "pse36" : "36-bit page size extensions",
            "clflush" : true,
            "mmx" : "multimedia extensions (MMX)",
            "fxsr" : "fast floating point save/restore",
            "sse" : "streaming SIMD extensions (SSE)",
            "sse2" : "streaming SIMD extensions (SSE2)",
            "syscall" : "fast system calls",
            "nx" : "no-execute bit (NX)",
            "x86-64" : "64bits extensions (x86-64)",
            "rep_good" : true,
            "nopl" : true,
            "xtopology" : true,
            "cpuid" : true,
            "tsc_known_freq" : true,
            "pni" : true,
            "cx16" : true,
            "x2apic" : true,
            "hypervisor" : true,
            "lahf_lm" : true,
            "pti" : true
          }
        },
        {
          "id" : "memory",
          "class" : "memory",
          "claimed" : true,
          "handle" : "DMI:1000",
          "description" : "System Memory",
          "physid" : "1000",
          "units" : "bytes",
          "size" : 1073741824,
          "capacity" : 1073741824,
          "configuration" : {
            "errordetection" : "multi-bit-ecc"
          },
          "capabilities" : {
            "ecc" : "Multi-bit error-correcting code (ECC)"
          },
          "children" : [
            {
              "id" : "bank",
              "class" : "memory",
              "claimed" : true,
              "handle" : "DMI:1100",
              "description" : "DIMM RAM",
              "vendor" : "Red Hat",
              "physid" : "0",
              "slot" : "DIMM 0",
              "units" : "bytes",
              "size" : 1073741824
            }
          ]
        },
        {
          "id" : "pci",
          "class" : "bridge",
          "claimed" : true,
          "handle" : "PCIBUS:0000:00",
          "description" : "Host bridge",
          "product" : "440FX - 82441FX PMC [Natoma]",
          "vendor" : "Intel Corporation",
          "physid" : "100",
          "businfo" : "pci@0000:00:00.0",
          "version" : "02",
          "width" : 32,
          "clock" : 33000000,
          "children" : [
            {
              "id" : "isa",
              "class" : "bridge",
              "claimed" : true,
              "handle" : "PCI:0000:00:01.0",
              "description" : "ISA bridge",
              "product" : "82371SB PIIX3 ISA [Natoma/Triton II]",
              "vendor" : "Intel Corporation",
              "physid" : "1",
              "businfo" : "pci@0000:00:01.0",
              "version" : "00",
              "width" : 32,
              "clock" : 33000000,
              "configuration" : {
                "latency" : "0"
              },
              "capabilities" : {
                "isa" : true
              }
            },
            {
              "id" : "ide",
              "class" : "storage",
              "claimed" : true,
              "handle" : "PCI:0000:00:01.1",
              "description" : "IDE interface",
              "product" : "82371SB PIIX3 IDE [Natoma/Triton II]",
              "vendor" : "Intel Corporation",
              "physid" : "1.1",
              "businfo" : "pci@0000:00:01.1",
              "version" : "00",
              "width" : 32,
              "clock" : 33000000,
              "configuration" : {
                "driver" : "ata_piix",
                "latency" : "0"
              },
              "capabilities" : {
                "ide" : true,
                "isa_compat_mode" : "ISA compatibility mode",
                "bus_master" : "bus mastering"
              }
            },
            {
              "id" : "usb",
              "class" : "bus",
              "claimed" : true,
              "handle" : "PCI:0000:00:01.2",
              "description" : "USB controller",
              "product" : "82371SB PIIX3 USB [Natoma/Triton II]",
              "vendor" : "Intel Corporation",
              "physid" : "1.2",
              "businfo" : "pci@0000:00:01.2",
              "version" : "01",
              "width" : 32,
              "clock" : 33000000,
              "configuration" : {
                "driver" : "uhci_hcd",
                "latency" : "0"
              },
              "capabilities" : {
                "uhci" : "Universal Host Controller Interface (USB1)",
                "bus_master" : "bus mastering"
              },
              "children" : [
                {
                  "id" : "usbhost",
                  "class" : "bus",
                  "claimed" : true,
                  "handle" : "USB:1:1",
                  "product" : "UHCI Host Controller",
                  "vendor" : "Linux 5.4.0-182-generic uhci_hcd",
                  "physid" : "1",
                  "businfo" : "usb@1",
                  "logicalname" : "usb1",
                  "version" : "5.04",
                  "configuration" : {
                    "driver" : "hub",
                    "slots" : "2",
                    "speed" : "12Mbit/s"
                  },
                  "capabilities" : {
                    "usb-1.10" : "USB 1.1"
                  },
                  "children" : [
                    {
                      "id" : "usb",
                      "class" : "input",
                      "claimed" : true,
                      "handle" : "USB:1:2",
                      "description" : "Human interface device",
                      "product" : "QEMU USB Tablet",
                      "vendor" : "QEMU",
                      "physid" : "1",
                      "businfo" : "usb@1:1",
                      "version" : "0.00",
                      "serial" : "42",
                      "configuration" : {
                        "driver" : "usbhid",
                        "maxpower" : "100mA",
                        "speed" : "12Mbit/s"
                      },
                      "capabilities" : {
                        "usb-2.00" : "USB 2.0"
                      }
                    }
                  ]
                }
              ]
            },
            {
              "id" : "bridge",
              "class" : "bridge",
              "claimed" : true,
              "handle" : "PCI:0000:00:01.3",
              "description" : "Bridge",
              "product" : "82371AB/EB/MB PIIX4 ACPI",
              "vendor" : "Intel Corporation",
              "physid" : "1.3",
              "businfo" : "pci@0000:00:01.3",
              "version" : "03",
              "width" : 32,
              "clock" : 33000000,
              "configuration" : {
                "driver" : "piix4_smbus",
                "latency" : "0"
              },
              "capabilities" : {
                "bridge" : true
              }
            },
            {
              "id" : "display",
              "class" : "display",
              "claimed" : true,
              "handle" : "PCI:0000:00:02.0",
              "description" : "VGA compatible controller",
              "product" : "GD 5446",
              "vendor" : "Cirrus Logic",
              "physid" : "2",
              "businfo" : "pci@0000:00:02.0",
              "version" : "00",
              "width" : 32,
              "clock" : 33000000,
              "configuration" : {
                "driver" : "cirrus",
                "latency" : "0"
              },
              "capabilities" : {
                "vga_controller" : true,
                "rom" : "extension ROM"
              }
            },
            {
              "id" : "network",
              "class" : "network",
              "claimed" : true,
              "handle" : "PCI:0000:00:03.0",
              "description" : "Ethernet controller",
              "product" : "Virtio network device",
              "vendor" : "Red Hat, Inc.",
              "physid" : "3",
              "businfo" : "pci@0000:00:03.0",
              "version" : "00",
              "width" : 64,
              "clock" : 33000000,
              "configuration" : {
                "driver" : "virtio-pci",
                "latency" : "0"
              },
              "capabilities" : {
                "msix" : "MSI-X",
                "bus_master" : "bus mastering",
                "cap_list" : "PCI capabilities listing",
                "rom" : "extension ROM"
              },
              "children" : [
                {
                  "id" : "virtio0",
                  "class" : "network",
                  "claimed" : true,
                  "description" : "Ethernet interface",
                  "physid" : "0",
                  "businfo" : "virtio@0",
                  "logicalname" : "ens3",
                  "serial" : "52:54:00:fe:d6:27",
                  "configuration" : {
                    "autonegotiation" : "off",
                    "broadcast" : "yes",
                    "driver" : "virtio_net",
                    "driverversion" : "1.0.0",
                    "ip" : "185.105.116.95",
                    "link" : "yes",
                    "multicast" : "yes"
                  },
                  "capabilities" : {
                    "ethernet" : true,
                    "physical" : "Physical interface"
                  }
                }
              ]
            },
            {
              "id" : "scsi",
              "class" : "storage",
              "claimed" : true,
              "handle" : "PCI:0000:00:04.0",
              "description" : "SCSI storage controller",
              "product" : "Virtio block device",
              "vendor" : "Red Hat, Inc.",
              "physid" : "4",
              "businfo" : "pci@0000:00:04.0",
              "version" : "00",
              "width" : 64,
              "clock" : 33000000,
              "configuration" : {
                "driver" : "virtio-pci",
                "latency" : "0"
              },
              "capabilities" : {
                "scsi" : true,
                "msix" : "MSI-X",
                "bus_master" : "bus mastering",
                "cap_list" : "PCI capabilities listing"
              },
              "children" : [
                {
                  "id" : "virtio1",
                  "class" : "disk",
                  "claimed" : true,
                  "handle" : "GUID:532a0761-6347-4b61-8618-9646c2f0c253",
                  "description" : "Virtual I/O device",
                  "physid" : "0",
                  "businfo" : "virtio@1",
                  "logicalname" : "/dev/vda",
                  "units" : "bytes",
                  "size" : 21474836480,
                  "configuration" : {
                    "driver" : "virtio_blk",
                    "guid" : "532a0761-6347-4b61-8618-9646c2f0c253",
                    "logicalsectorsize" : "512",
                    "sectorsize" : "512"
                  },
                  "capabilities" : {
                    "gpt-1.00" : "GUID Partition Table version 1.00",
                    "partitioned" : "Partitioned disk",
                    "partitioned:gpt" : "GUID partition table"
                  },
                  "children" : [
                    {
                      "id" : "volume:0",
                      "class" : "volume",
                      "claimed" : true,
                      "handle" : "GUID:c3404df0-9716-4b78-9823-4055cd0f0d55",
                      "description" : "BIOS Boot partition",
                      "vendor" : "EFI",
                      "physid" : "1",
                      "businfo" : "virtio@1,1",
                      "logicalname" : "/dev/vda1",
                      "dev" : "252:1",
                      "serial" : "c3404df0-9716-4b78-9823-4055cd0f0d55",
                      "capacity" : 1048064,
                      "capabilities" : {
                        "nofs" : "No filesystem"
                      }
                    },
                    {
                      "id" : "volume:1",
                      "class" : "volume",
                      "claimed" : true,
                      "handle" : "GUID:bb7e9eea-541b-4538-9c0f-1dfdfea7951b",
                      "description" : "EXT4 volume",
                      "vendor" : "Linux",
                      "physid" : "2",
                      "businfo" : "virtio@1,2",
                      "logicalname" : ["/dev/vda2", "/"],
                      "dev" : "252:2",
                      "version" : "1.0",
                      "serial" : "8bd4f97b-b2b8-4f05-bcc2-9e343788402a",
                      "size" : 21471690752,
                      "configuration" : {
                        "created" : "2024-05-28 20:05:00",
                        "filesystem" : "ext4",
                        "lastmountpoint" : "/",
                        "modified" : "2024-05-28 20:19:19",
                        "mount.fstype" : "ext4",
                        "mount.options" : "rw,relatime,errors=remount-ro",
                        "mounted" : "2024-05-28 20:16:29",
                        "state" : "mounted"
                      },
                      "capabilities" : {
                        "journaled" : true,
                        "extended_attributes" : "Extended Attributes",
                        "large_files" : "4GB+ files",
                        "huge_files" : "16TB+ files",
                        "dir_nlink" : "directories with 65000+ subdirs",
                        "64bit" : "64bit filesystem",
                        "extents" : "extent-based allocation",
                        "ext4" : true,
                        "ext2" : "EXT2/EXT3",
                        "initialized" : "initialized volume"
                      }
                    }
                  ]
                }
              ]
            },
            {
              "id" : "generic",
              "class" : "generic",
              "claimed" : true,
              "handle" : "PCI:0000:00:05.0",
              "description" : "Unclassified device",
              "product" : "Virtio memory balloon",
              "vendor" : "Red Hat, Inc.",
              "physid" : "5",
              "businfo" : "pci@0000:00:05.0",
              "version" : "00",
              "width" : 64,
              "clock" : 33000000,
              "configuration" : {
                "driver" : "virtio-pci",
                "latency" : "0"
              },
              "capabilities" : {
                "bus_master" : "bus mastering",
                "cap_list" : "PCI capabilities listing"
              },
              "children" : [
                {
                  "id" : "virtio2",
                  "class" : "generic",
                  "description" : "Virtual I/O device",
                  "physid" : "0",
                  "businfo" : "virtio@2",
                  "configuration" : {
                    "driver" : "virtio_balloon"
                  }
                }
              ]
            }
          ]
        },
        {
          "id" : "pnp00:00",
          "class" : "system",
          "claimed" : true,
          "product" : "PnP device PNP0b00",
          "physid" : "1",
          "configuration" : {
            "driver" : "rtc_cmos"
          },
          "capabilities" : {
            "pnp" : true
          }
        },
        {
          "id" : "pnp00:01",
          "class" : "input",
          "claimed" : true,
          "product" : "PnP device PNP0303",
          "physid" : "2",
          "configuration" : {
            "driver" : "i8042 kbd"
          },
          "capabilities" : {
            "pnp" : true
          }
        },
        {
          "id" : "pnp00:02",
          "class" : "input",
          "claimed" : true,
          "product" : "PnP device PNP0f13",
          "physid" : "3",
          "configuration" : {
            "driver" : "i8042 aux"
          },
          "capabilities" : {
            "pnp" : true
          }
        },
        {
          "id" : "pnp00:03",
          "class" : "storage",
          "claimed" : true,
          "product" : "PnP device PNP0700",
          "physid" : "4",
          "capabilities" : {
            "pnp" : true
          }
        },
        {
          "id" : "pnp00:04",
          "class" : "communication",
          "claimed" : true,
          "product" : "PnP device PNP0501",
          "physid" : "5",
          "configuration" : {
            "driver" : "serial"
          },
          "capabilities" : {
            "pnp" : true
          }
        }
      ]
    }
  ]
}
]

**Comment by Aidaho12** [comment]
Thank you, will check

**Comment by Aidaho12** [comment]
Try to edit the file /var/www/haproxy-wi/app/routes/server/routes.py on line 134. Insetead of the line:
```
	system_info = json.loads(sys_info_returned)
```
past these:
```
	try:
		system_info = json.loads(sys_info_returned)
	except Exception:
		system_info = json.loads(sys_info_returned)
```

**Comment by JohnnyFastfox** [comment]
Thx, even tho you've mentioned the wrong server.py file (found it in modules) I've managed to change the lines.

I'm embarrassed to admit but how do I restart roxy-wi? Via Python?

**Comment by Aidaho12** [comment]
Reload apache for it: systemctl reload apache2 (or httpd)

**Comment by JohnnyFastfox** [comment]
Ok, I did that and problem persists :(

Pavel Loginov ***@***.***> schrieb am Mi., 29. Mai 2024,
18:55:

**Comment by Aidaho12** [comment]
The same error?

**Comment by JohnnyFastfox** [comment]
Yes, nothing changed actually. I can see the request in the access.log but no correlated error in the error.log but the error in the frontend is still the same.

**Comment by Aidaho12** [comment]
Have you pressed the refresh button?) if yes open Dev tool in your browser and open response when trying to refresh

**Comment by JohnnyFastfox** [comment]
Of course I did, also cleaned cache etc and the response to the xhr request is the same: "error: Cannot update server info: list indices must be integers or slices, not str"

**Comment by Aidaho12** [comment]
Can you provide access to your Roxy-WI for investigate?

**Comment by JohnnyFastfox** [comment]
Yes, it's https://94.142.141.158/ but how should I provide credentials?

**Comment by Aidaho12** [comment]
Write me to ***@***.***, I will look tomorrow

**Comment by JohnnyFastfox** [comment]
Your mail address got censored

**Comment by Aidaho12** [comment]
What do you mean?
--
Отправлено из Mail.ru для Android среда, 29 мая 2024г., 21:41 +03:00 от JohnnyFastfox  ***@***.*** :

**Comment by JohnnyFastfox** [comment]
Look at your provided mail address, it got censored by GitHub.

**Comment by Aidaho12** [comment]
I see, you can find it in my profile

**Comment by Aidaho12** [comment]
This bug for old system. Do you use newer?

**Comment by JohnnyFastfox** [comment]
Yes, I'm using Ubuntu 22

**Comment by Aidaho12** [comment]
Fixed in the new release
