### ISSUE TITLE
Unable to create and generate new Let Encrypt certificate since v7.2.0

### ISSUE THREAD

**Issue by rhagglund** [roxy-wi/roxy-wi#388]
Hello!

Since updated to 7.2.0 I no longer can create Lets encrypt SLL certs. When I try to generate the cert nothing is happening, nothing is loading. The text "Please do not close or refresh the page. Wait until the job is completed. This may take some time" is still there but I dont reseive any info if it passed, failed or anything.

The "loading bar" in the top of the page is running very quickly (1 sec) like when nothing is answearing.

See error-logs pasted

[error.log](https://github.com/user-attachments/files/16283031/error.log)
[roxy-wi.error.log](https://github.com/user-attachments/files/16283032/roxy-wi.error.log)

**Comment by Aidaho12** [comment]
Hello, fixed here https://github.com/roxy-wi/roxy-wi/commit/74562243f3d18caa0c03ed797cec45ee71ba90c0
