### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by witbooic** [roxy-wi/roxy-wi#389]
Hi Below is the error I receive when trying to execute create_db.py during install process.

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3263, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3604, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/haproxy-wi/./create_db.py", line 717, in <module>
    create_tables()
  File "/var/www/haproxy-wi/modules/db/db_model.py", line 782, in create_tables
    with conn:
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3231, in __enter__
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3266, in connect
    self._initialize_connection(self._state.conn)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3088, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 196, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3263, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3604, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file

**Comment by Aidaho12** [comment]
Hello,

Check does the folder /var/lib/roxy-wi exist and has correct (apache user) owner and permission

**Comment by witbooic** [comment]
Hi thanks for your response. roxy-wi does not exist in /var/lib/ it exists in /etc/

**Comment by Aidaho12** [comment]
Try to create the folder

**Comment by witbooic** [comment]
Hi I did I am getting internal server error now when open in browser below is the errors I receive 

[Fri Jul 26 08:21:27.805444 2024] [wsgi:error] [pid 4882:tid 5063] [remote 10.20.22.79:56150] mod_wsgi (pid=4882): Failed to exec Python script file '/var/www/haproxy-wi/login.py'.
[Fri Jul 26 08:21:27.805593 2024] [wsgi:error] [pid 4882:tid 5063] [remote 10.20.22.79:56150] mod_wsgi (pid=4882): Exception occurred processing WSGI script '/var/www/haproxy-wi/login.py'.
[Fri Jul 26 08:21:27.805681 2024] [wsgi:error] [pid 4882:tid 5063] [remote 10.20.22.79:56150] Traceback (most recent call last):
[Fri Jul 26 08:21:27.805702 2024] [wsgi:error] [pid 4882:tid 5063] [remote 10.20.22.79:56150]   File "/var/www/haproxy-wi/login.py", line 4, in <module>
[Fri Jul 26 08:21:27.805710 2024] [wsgi:error] [pid 4882:tid 5063] [remote 10.20.22.79:56150]     from app import app, login_manager, cache
[Fri Jul 26 08:21:27.805723 2024] [wsgi:error] [pid 4882:tid 5063] [remote 10.20.22.79:56150] ModuleNotFoundError: No module named 'app'

**Comment by Aidaho12** [comment]
Looks like something wrong with http config. Check this section:
```
    WSGIDaemonProcess roxy-wi-app request-timeout=60 display-name=%{GROUP} user=apache group=apache processes=10 threads=20
    WSGIScriptAlias /app /var/www/haproxy-wi/app/app.wsgi
    WSGIApplicationGroup %{GLOBAL}

    <Directory /var/www/haproxy-wi/app/>
        WSGIProcessGroup roxy-wi-app
        WSGIApplicationGroup %{GLOBAL}
        Order deny,allow
        Allow from all
    </Directory>
```

**Comment by witbooic** [comment]
Hi Thanks all working now

I added below line:

  WSGIDaemonProcess roxy-wi-app request-timeout=60 display-name=%{GROUP} user=apache group=apache processes=10 threads=20

Closing issue now
