### ISSUE TITLE
Feature request: ACME protocol and DNS API support for SSL

### ISSUE THREAD

**Issue by mertcangokgoz** [roxy-wi/roxy-wi#394]
A support can be considered for those who want to get ssl through acme and dnsapi whose domain address is in cloudflare, route53 or a different cloud provider.

Which problem does it solve?

- SSL can be easily obtained via the API using the ACME protocol, and a different provider can be chosen to avoid lets encrypt restrictions.

the most active tool we know of: https://github.com/acmesh-official/acme.sh

**Comment by Aidaho12** [comment]
Looks like we should do it :)

**Comment by Aidaho12** [comment]
Added https://github.com/roxy-wi/roxy-wi/releases/tag/v8.1.1
