### ISSUE TITLE
Error message roxy-wi-key

### ISSUE THREAD

**Issue by ygamac** [roxy-wi/roxy-wi#395]
Hello,

I cannot show roxy web page, I've got an error : 
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

I've got this error in the apache's error file : 
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/roxy-wi/keys/roxy-wi-key'

Can you help me ?

Regards

**Comment by Aidaho12** [comment]
Hello, please read update guid

**Comment by ygamac** [comment]
Hello,

I didn't find it on the documentation page. Can you give me a link ?

**Comment by Aidaho12** [comment]
it's here https://roxy-wi.org/update-guide

**Comment by ygamac** [comment]
It's not completed, after that I have a new error : 
Bad Request
The browser (or proxy) sent a request that this server could not understand.

I searched more information about that but nothing were present in the log files.
Regards

**Comment by Aidaho12** [comment]
Have you edited apache roxy-wi.conf before update?

**Comment by ygamac** [comment]
I've done a new install, and it's working now. I have to use this part of the update doc [Updating to version 8](https://roxy-wi.org/update-guide#8).

For python dependencies I have to fix setuptools version with pip3.10 install --upgrade setuptools==70.0.0.

Regards

**Comment by ygamac** [comment]
I didn't have the licence raw (https://roxy-wi.org/howto/get-licence).
Is there another way to registered my licence ?

Regards

**Comment by Aidaho12** [comment]
If you have subscription, but don't have a license try to use your password as the license

**Comment by ygamac** [comment]
My subscription plan is blocked : 

Plan | Enterprise
Status | Blocked
Pay Method | Patreon

Any idea ?

**Comment by Aidaho12** [comment]
Could you send an email, what you uses for subscription

**Comment by ygamac** [comment]
It's OK now, thanks.

**Comment by Aidaho12** [comment]
Glad to hear it!
