### ISSUE TITLE
How to install on Centos7.6 ?

### ISSUE THREAD

**Issue by renforwards** [roxy-wi/roxy-wi#396]
Hi, I want to install woxy-wi on centos 7.6, some error happen.

This is my produce env, So I cannot change to newer centos.

[root@localhost roxy-wi]# yum install roxy-wi roxy-wi-checker roxy-wi-smon roxy-wi-metrics roxy-wi-keep_alive roxy-wi-portscanner roxy-wi-socket
......
---> Package libtommath.x86_64 0:0.42.0-6.el7 will be installed
---> Package roxy-wi.noarch 0:8-0.1 will be installed
--> Processing Dependency: python3.11-pip for package: roxy-wi-8-0.1.noarch
--> Processing Dependency: python3.11-mod_wsgi for package: roxy-wi-8-0.1.noarch
--> Processing Dependency: python3.11-ldap for package: roxy-wi-8-0.1.noarch
--> Processing Dependency: python3.11-devel for package: roxy-wi-8-0.1.noarch
--> Processing Dependency: python3.11 for package: roxy-wi-8-0.1.noarch
---> Package systemd.x86_64 0:219-78.el7 will be updated
--> Processing Dependency: systemd = 219-78.el7 for package: systemd-sysv-219-78.el7.x86_64
---> Package systemd.x86_64 0:219-78.el7_9.9 will be an update
---> Package systemd-libs.x86_64 0:219-78.el7 will be updated
---> Package systemd-libs.x86_64 0:219-78.el7_9.9 will be an update
--> Running transaction check
---> Package roxy-wi.noarch 0:8-0.1 will be installed
--> Processing Dependency: python3.11-pip for package: roxy-wi-8-0.1.noarch
--> Processing Dependency: python3.11-mod_wsgi for package: roxy-wi-8-0.1.noarch
--> Processing Dependency: python3.11-ldap for package: roxy-wi-8-0.1.noarch
--> Processing Dependency: python3.11-devel for package: roxy-wi-8-0.1.noarch
--> Processing Dependency: python3.11 for package: roxy-wi-8-0.1.noarch
---> Package systemd-sysv.x86_64 0:219-78.el7 will be updated
---> Package systemd-sysv.x86_64 0:219-78.el7_9.9 will be an update
--> Finished Dependency Resolution
Error: Package: roxy-wi-8-0.1.noarch (Roxy-WI)
           Requires: python3.11-mod_wsgi
Error: Package: roxy-wi-8-0.1.noarch (Roxy-WI)
           Requires: python3.11
Error: Package: roxy-wi-8-0.1.noarch (Roxy-WI)
           Requires: python3.11-ldap
Error: Package: roxy-wi-8-0.1.noarch (Roxy-WI)
           Requires: python3.11-pip
Error: Package: roxy-wi-8-0.1.noarch (Roxy-WI)
           Requires: python3.11-devel
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
[root@localhost roxy-wi]# 

How to solve them? Actually , I have installed python3.12 on my os, and it works fine.

If I want to install by manual, How should I do?

**Comment by Aidaho12** [comment]
Hi, Roxy-WI uses python3.11 on Centos. So you have to install it

**Comment by renforwards** [comment]
> Hi, Roxy-WI uses python3.11 on Centos. So you have to install it

My os is centos7.6， so there is no python3.11(  python3.11-ldap,python3.11-pip,python3.11-devel ) on yum repo. 

 I have installed it by manual, I means I compile it on my os.

So how to solve those error ?

Hope you replay!

**Comment by Aidaho12** [comment]
There is a way https://computingforgeeks.com/install-python-3-on-centos-rhel-7/
