### ISSUE TITLE
WebUI validation error on net-iface name

### ISSUE THREAD

**Issue by al-indigo** [roxy-wi/roxy-wi#402]
You have the following regex to validate net-iface name: 
https://github.com/roxy-wi/roxy-wi/blob/3d642a61c4749704004c73f085a800e5d166b73f/app/static/js/ha.js#L185

Modern versions of XenServer and XCP-ng make their net-ifaces in guest systems look like enX0, enX1 etc so this regex fails. You should respect upper-case too there. The only way to make it work without changing your sources is to rename net-iface, but it's a wrong approach.

**Comment by Aidaho12** [comment]
Thank you, will be fixed

**Comment by Aidaho12** [comment]
Fixed https://github.com/roxy-wi/roxy-wi/releases/tag/v8.1.1
