### ISSUE TITLE
HAProxy SSL FrontEnd Not Working

### ISSUE THREAD

**Issue by jcervantes-sipecom** [roxy-wi/roxy-wi#405]
When creating a SSL FrontEnd with SSL Offloading, and select el Certificate, the created FrontEnd does not set the SSL parameters and Certificate:

1) Create a SSL FrontEnd

![image](https://github.com/user-attachments/assets/92dd66ae-0622-499c-8a5f-feaacad3cfc8)

2) Select SSL Offloading and select the certificate uploaded before:

![image](https://github.com/user-attachments/assets/fe8e790b-834d-4861-ad53-2a34a3e9c0fb)

3) If see the created SSL Fronted, you should see that the bind doesn't have SSL Parameters (ssl crt) and the PEM Path

![image](https://github.com/user-attachments/assets/281935b0-cf83-4c5a-8b86-df8323eb737c)

4) We need to manually add these parameters for working with HTTPS/SSL FrontEnd:

![image](https://github.com/user-attachments/assets/5cf4d0a1-b3b5-4e7f-9703-40a77c9ef936)

**Comment by Aidaho12** [comment]
Thanks, will be fixed

**Comment by Aidaho12** [comment]
Fixed https://github.com/roxy-wi/roxy-wi/commit/05279fa64fefeee3dae11ef61983d090a9e14032
