### ISSUE TITLE
Haproxy don't comunicate with roxy-wi 

### ISSUE THREAD

**Issue by ByakuraRinne** [roxy-wi/roxy-wi#408]
Hello, I just installed Roxy-WI using Docker and connected my server. I added the SSH credentials, and everything seems good, but I’m having an issue: the status never shows as "OK" or "Start"—it always says "Stop." Can you help me? Thanks in advance!
![{F8C2C4C2-221E-4D05-9AA6-B8E2036D93B3}](https://github.com/user-attachments/assets/ebd948a6-393d-41e4-8152-e01730841b1c)

**Comment by Aidaho12** [comment]
Hello, check 1999 port. Does it open?

**Comment by ByakuraRinne** [comment]
Im sorry 
on what roxy or haproxy ?

**Comment by Aidaho12** [comment]
On haproxy

**Comment by ByakuraRinne** [comment]
i don't think so 
do i need to have a spesific config for haproxy ?
here mine 
`global
    log /dev/log local0
    maxconn 2000

defaults
    log global
    mode tcp
    option tcplog
    option dontlognull
    timeout connect 5s
    timeout client 50s
    timeout server 50s

# Frontend pour IMAP (ports 143 et 993)
frontend imap_front
    bind *:143  # IMAP non sécurisé
    bind *:993  # IMAP sécurisé (IMAPS)
    default_backend imap_backend

backend imap_backend
    server imap_server 192.168.2.124:143 check
    server imap_secure_server 192.168.2.124:993 check

# Frontend pour SMTP (ports 25, 465 et 587)
frontend smtp_front
    bind *:25   # SMTP non sécurisé
    bind *:465  # SMTP sécurisé (SMTPS)
    bind *:587  # SMTP avec STARTTLS
    default_backend smtp_backend

backend smtp_backend
    server smtp_server 192.168.2.124:25 check
    server smtps_server 192.168.2.124:465 check
    server smtp_starttls_server 192.168.2.124:587 check

# Enable stats page for Roxy-WI
frontend stats
    bind *:8085  # Roxy-WI stats page (adjust port if necessary)
    mode http     # Change mode to HTTP
    stats enable
    stats uri /stats  # URI for stats page
    stats refresh 10s  # Auto-refresh interval for the page
    stats auth admin:password  # Replace with your desired username and password`

**Comment by Aidaho12** [comment]
Yes, haproxy config must have sock port. You can read how to on the site

**Comment by ByakuraRinne** [comment]
thank a lot
