### ISSUE TITLE
Cannot create HAProxy section: Something wrong with installation, check Apache logs for details

### ISSUE THREAD

**Issue by ByakuraRinne** [roxy-wi/roxy-wi#409]
Hi (again) when i try to add config to haproxy i have this error 
![{CE68F8B2-B46E-4A1E-A665-EC91C9D2FCD5}](https://github.com/user-attachments/assets/d68b57dd-fffc-4bd9-8fc8-7ca353e41667)
and when i want to know the log 
![{C24867AE-9BEB-4999-ABE7-51D3A30CFDEF}](https://github.com/user-attachments/assets/422c4e53-82ea-4d29-a701-bf2e1e320c30)
many thanks for your help

**Comment by Aidaho12** [comment]
Check logs in console

**Comment by ByakuraRinne** [comment]
can you tell me the exat path of the file please ?

**Comment by ByakuraRinne** [comment]
i find that :
``[root@ecad3d74c3be /]# cat /var/log/httpd/error_log
[Mon Dec 23 05:30:22.782313 2024] [suexec:notice] [pid 9:tid 140653016185152] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Mon Dec 23 05:30:22.816984 2024] [lbmethod_heartbeat:notice] [pid 9:tid 140653016185152] AH02282: No slotmem from mod_heartmonitor
[Mon Dec 23 05:30:22.839653 2024] [mpm_event:notice] [pid 9:tid 140653016185152] AH00489: Apache/2.4.37 (CentOS Stream) OpenSSL/1.1.1k mod_wsgi/4.9.4 Python/3.11 configured -- resuming normal operations
[Mon Dec 23 05:30:22.839734 2024] [core:notice] [pid 9:tid 140653016185152] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Mon Dec 23 05:39:38.830267 2024] [suexec:notice] [pid 9:tid 140514994080064] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
[Mon Dec 23 05:39:38.860474 2024] [lbmethod_heartbeat:notice] [pid 9:tid 140514994080064] AH02282: No slotmem from mod_heartmonitor
[Mon Dec 23 05:39:38.861869 2024] [core:warn] [pid 9:tid 140514994080064] AH00098: pid file /etc/httpd/run/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Mon Dec 23 05:39:38.862023 2024] [cgid:error] [pid 17:tid 140514994080064] (98)Address already in use: AH01243: Couldn't bind unix domain socket /etc/httpd/run/cgisock.9
[Mon Dec 23 05:39:38.862497 2024] [wsgi:warn] [pid 9:tid 140514994080064] (98)Address already in use: mod_wsgi (pid=9): Removing stale unix domain socket '/etc/httpd/run/wsgi.9.0.1.sock'.
[Mon Dec 23 05:39:38.879297 2024] [mpm_event:notice] [pid 9:tid 140514994080064] AH00489: Apache/2.4.37 (CentOS Stream) OpenSSL/1.1.1k mod_wsgi/4.9.4 Python/3.11 configured -- resuming normal operations
[Mon Dec 23 05:39:38.879366 2024] [core:notice] [pid 9:tid 140514994080064] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Mon Dec 23 05:39:38.879526 2024] [cgid:crit] [pid 9:tid 140514994080064] AH01238: cgid daemon failed to initialize``

**Comment by Aidaho12** [comment]
First log was correct:) and there was the answer

**Comment by ByakuraRinne** [comment]
sorry but i don't understand the error can you help me ?

**Comment by Aidaho12** [comment]
I'm sorry, but no. Supporting is paid

**Comment by ByakuraRinne** [comment]
sry again but after an install on centos i can't connect my server here an image : 
![{0465D4D3-8AD5-48D5-B5D0-3936C6D75B31}](https://github.com/user-attachments/assets/4d405b09-18f7-496a-9a92-a824af9cf8d7)

thanks for your help ! 
and merry christmas
