### ISSUE TITLE
(13, 'Permission denied')

### ISSUE THREAD

**Issue by T9139903** [roxy-wi/roxy-wi#7]
Hello, After successful setup and run on Centos7, and added the SSH keys from centos to haproxy server (without passcode), and tested SSH connection successfully, I cannot see any server and when I add servers to the list I get (13, 'Permission denied') error. What I'm missing?!!!

**Comment by mhammady** [comment]
![image](https://user-images.githubusercontent.com/11185735/39446323-1b288420-4c8c-11e8-9f9a-df4ed6baf4f0.png)

**Comment by Aidaho12** [comment]
User root?
--
Отправлено из Mail.Ru для Android вторник, 01 мая 2018г., 01:35 +06:00 от mhammady  notifications@github.com :
